Make removing policy-rc.d more robust

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,17 @@
 #!/bin/sh
 
-# Make sure configuring packages do not start any services
+set -e  # Exit on error
+
+at_exit() {
+    if $policyd ; then
+       rm -f /usr/sbin/policy-rc.d
+    fi
+    policyd=false
+}
+
+# Make sure configuring packages do not start any services.  Also make
+# sure we remove policy-rc.d only if we created it.
+trap at_exit HUP INT TERM EXIT
 if [ ! -e /usr/sbin/policy-rc.d ] ; then
     cat > /usr/sbin/policy-rc.d <<EOF
 #!/bin/sh
@@ -11,12 +22,8 @@ EOF
 else
     policyd=false
 fi
+
 for f in /usr/lib/freedombox/setup.d/* ; do
     echo "running $f"
     $f
 done
-
-# Allow services to start after upgrading
-if $policyd ; then
-    rm /usr/sbin/policy-rc.d
-fi
